package edu.purdue.maptak.admin.data;
import java.util.*;

public class TakObject {

    /** Main label of the tak. Optional. */
    private String label;

    /** Latitude and longitude of the tak. Required. */
    private double latitude, longitude;

    /** UUID of the tak, generated by the server. Null or required */
    private UUID uuid;

    /** Metadata about the tak */
    private Map<String, String> metadata;

    /** User who created the tak. Generated by the server. */
    private int createdBy;

    /** Unix timestamp of the date the server first registers the tak */
    private long createdOn;

    /** Constructor if everything is currently known */
    public TakObject(String label, double lat, double lng, UUID uuid, int owner, long date) {
        this.label = label;
        this.latitude = lat;
        this.longitude = lng;
        this.uuid = uuid;
        this.createdBy = owner;
        this.createdOn = date;
        this.metadata = new HashMap<String, String>();
    }

    /** Minimum constructor if the UUID is known */
    public TakObject(double lat, double lng, UUID uuid) {
        this(null, lat, lng, uuid, -1, -1);
    }

    /** Minimum constructor if the UUID is not known */
    public TakObject(double lat, double lng) {
        this(null, lat, lng, null, -1, -1);
    }

    /** Returns the latitude of the given tak */
    public double getLatitude() {
        return this.latitude;
    }

    /** Returns the longitude of the given tak */
    public double getLongitude() {
        return longitude;
    }

    /** Returns the UUID which keys this object in the master server database.
     *  Warning: This WILL COMMONLY RETURN NULL if the object was created without the UUID
     *  being known. */
    public UUID getUUID() {
        return this.uuid;
    }

    /** Returns all of the keys mapped by this tak's metadata */
    public Set<String> getMetadataKeys() {
        return metadata.keySet();
    }

    /** Returns all of the values mapped by this tak's metadata */
    public Set<String> getMetadataValues() {
        return new HashSet<String>(metadata.values());
    }

    /** Returns a value mapped by the given key to this tak's metadata */
    public String getMetadataValue(String key) {
        return metadata.get(key);
    }

    /** Returns the userid of the user who created the tak */
    public int getUserID() {
        return this.createdBy;
    }

    /** Returns the UNIX timestamp of when the tak was first registered to the server */
    public long getCreationTime() {
        return this.createdOn;
    }

    /** Sets the latitude of the given tak */
    public void setLatitude(double lat) {
        this.latitude = lat;
    }

    /** Sets the latitude of the given tak */
    public void setLongitude(double lng){
        this.longitude = lng;
    }

    /** Creates a new key-value pair in the tak's metadata */
    public void addMetadata(String key, String value) {
        this.metadata.put(key, value);
    }

    /** Sets the userid of the tak */
    public void setUserID(int userId) {
        this.createdBy = userId;
    }

    /** Sets the creation time of the tak */
    public void setCreationTime(long creationTime) {
        this.createdOn = creationTime;
    }

}
